"""initial schema

Revision ID: ab02b8a47a49
Revises: 
Create Date: 2026-07-01 15:34:00.953395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab02b8a47a49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'In Progress', 'On Hold', 'Completed', 'Cancelled', name='project_status'), nullable=False),
    sa.Column('type', sa.Enum('Paid', 'Presales', 'Internal', 'Support', name='project_type'), nullable=True),
    sa.Column('priority', sa.Enum('High', 'Medium', 'Low', name='project_priority'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('slack', 'excel', 'manual', name='project_source'), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('practice', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('resources',
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('availability', sa.Enum('Available', 'Busy', 'On Leave', name='resource_availability'), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Assigned', 'In Progress', 'Completed', 'Removed', name='assignment_status'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('slack_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('slack_user_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ts', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_events')
    op.drop_table('assignments')
    op.drop_table('resources')
    op.drop_table('projects')
    # ### end Alembic commands ###
